---
ingressController:
  installCRDs: false

clustertelemetry:
  enabled: true

ingressController:
  image:
    repository: ghcr.io/thspinto/kubernetes-ingress-controller # TODO: go back to official release after https://github.com/Kong/kubernetes-ingress-controller/pull/926
    tag: latest

image:
  repository: arm64v8/kong

proxy:
  stream:
    - containerPort: 9443
      servicePort: 9443
      parameters:
        - ssl
  ingress: # creating this ingress to use the dns record as CNAME for internal TCP routes
    enabled: true
    hosts:
      - internal.thsp.dev
    annotations:
      kubernetes.io/ingress.class: "kong"
