---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: argocd/infrastructure/external-dns
    repoURL: https://github.com/thspinto/rpi-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
