---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: argocd/infrastructure/kong
    repoURL: https://github.com/thspinto/rpi-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
