---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-exporter
spec:
  selector:
    matchLabels:
      app: mqtt-exporter
  template:
    metadata:
      labels:
        app: mqtt-exporter
    spec:
      containers:
      - name: mqtt-exporter
        image: thspinto/mqtt-exporter
        ports:
          - name: metrics
            containerPort: 9000
            protocol: TCP
        env:
        - name: MQTT_TOPIC
          value: home/OpenMQTTGateway/#
        - name: LOG_LEVEL
          value: DEBUG
        - name: MQTT_ADDRESS
          value: mosquitto
        - name: MQTT_USERNAME
          value: monitor
        - name: MQTT_CLIENT_ID
          value: exporter
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mosquitto
              key: monitor
        livenessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-exporter
  labels:
    app: mqtt-exporter
    app: mqtt-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: mqtt-exporter
    app: mqtt-exporter
