---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mqtt-exporter
  labels:
    app: mqtt-exporter
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: mqtt-exporter
