# This playbook applies the basic RBP OS configuration
---
- hosts: all
  become: yes
  become_method: sudo

  pre_tasks:
  - name: Check for Additional Storage
    stat:
      path: /dev/sda
    register: additional_storage

  roles:
  - mikolak-net.raspi_config
  - oefenweb.ufw

  tasks:
  - name: Disabling HDMI Port
    lineinfile:
      path: /etc/rc.local
      regexp: '^/usr/bin/tvservice'
      line: '/usr/bin/tvservice -o'
      insertafter: '^exit'
      state: present

  # Issue: https://github.com/raspberrypi/linux/issues/2810
  - name: Configure dirty background ratio
    ansible.posix.sysctl:
      name: vm.dirty_background_ratio
      value: '5'
      state: present
    notify: reboot

  - name: Configure dirty ratio
    ansible.posix.sysctl:
      name: vm.dirty_ratio
      value: '80'
      state: present
    notify: reboot

  # Mount additional storage
  - name: Mount extra storage
    mount:
      path: /mnt/storage
      src: /dev/sda
      fstype: ext4
      state: mounted
    when: additional_storage.stat.isblk is defined and additional_storage.stat.isblk


  - name: Enable cgroup via boot commandline if not already enabled
    lineinfile:
      path: /boot/cmdline.txt
      backrefs: yes
      regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
      line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    notify: reboot

  - name: Enable arm 64bit
    lineinfile:
      path: /boot/config.txt
      regexp: '^arm_64bit'
      line: 'arm_64bit=1'
      state: present
    notify: reboot

  handlers:
  - name: reboot
    reboot:
